server:
  port: 8082
spring:
  application:
    name: orderserv-service
  datasource:
    url: jdbc:mysql://47.101.180.128:3306/fs_orderserv?characterEncoding=utf8
    username: root
    password: 1x234g
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  mapper-locations: classpath*:/mapper/*.xml